checks and fixes for apk artifact path

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -89,17 +89,23 @@ build_release_apk:
     - echo "Building release apk for new tag $CI_COMMIT_TAG ..."
     - chmod +x ./gradlew
     - ./gradlew assembleRelease
+    - ls -l $APK_PATH
     - export RELEASE_APK=$(find "$APK_PATH" -name "*.apk")
     - |
       if [ -z "$RELEASE_APK" ]; then
         echo "Error: Failed to find the built APK!"
         exit 1
       fi
+    - |
+      if [ ! -f "$RELEASE_APK" ]; then
+        echo "Error: Failed to find the APK file!"
+        exit 1
+      fi
     - export RELEASE_APK_NAME=$(basename "$RELEASE_APK")
-    - echo "Successfully built APK $RELEASE_APK_NAME"
+    - echo "Successfully built APK $RELEASE_APK_NAME to $RELEASE_APK"
   artifacts:
     paths:
-      - $RELEASE_APK
+      - "$RELEASE_APK"
     expire_in: 7 days
 
 create_release:
